/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MobilController;
import java.util.List;
import model.Mobil;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GaryFaldi
 */
public class AdminDashboardMobil extends javax.swing.JFrame {

    private MobilController controller;
    private DefaultTableModel tableModel;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboardMobil() {
        initComponents();
        controller = new MobilController();
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        "Tersedia", "Disewa"
            }));
        initTable();
        loadData();
        tblMobil.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblMobilMouseClicked(evt);
        }
    });
        
        cariButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cariButtonActionPerformed(evt);
        }
    });
        
        DefaultTableModel model = (DefaultTableModel) tblMobil.getModel();
        model.setColumnIdentifiers(new String[]{"Plat", "Tipe", "Merk", "Harga Sewa", "Status"});
    }
    private void initTable() {
        // Buat model tabel dengan kolom yang sesuai
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Plat Nomor");
        tableModel.addColumn("Tipe");
        tableModel.addColumn("Merk");
        tableModel.addColumn("Harga Sewa");
        tableModel.addColumn("Status");
        
        tblMobil.setModel(tableModel);
    }
    private void loadData() {
        // Ambil data dari controller
        List<Mobil> daftarMobil = controller.getAllMobil();
        
        // Bersihkan tabel
        tableModel.setRowCount(0);
        
        // Isi tabel dengan data baru
        for (Mobil m : daftarMobil) {
            String statusStr = convertIntToStatus(m.getStatus());
            tableModel.addRow(new Object[] {
                m.getPlat(), 
                m.getTipe(), 
                m.getMerk(), 
                m.getHargaSewa(), 
                statusStr
            });
        }
    }


    private int convertStatusToInt(String statusText) {
        return statusText.equals("Tersedia") ? 1 : 0;
    }

    private String convertIntToStatus(int statusValue) {
        return statusValue == 1 ? "Tersedia" : "Disewa";
    }

    
    public void setTableData(List<Mobil> daftarMobil) {
        DefaultTableModel model = (DefaultTableModel) tblMobil.getModel();
        model.setRowCount(0);
        for (Mobil m : daftarMobil) {
            String statusStr = convertIntToStatus(m.getStatus());
            model.addRow(new Object[] {
            m.getPlat(), 
            m.getTipe(), 
            m.getMerk(), 
            m.getHargaSewa(), 
            statusStr  // Gunakan string status
        });
        }
    }
    
    
    
    public void clearForm() {
    platTextField.setText("");
    tipeTextField.setText("");
    merkTextField.setText("");
    hargaTextField.setText("");
    cmbStatus.setSelectedIndex(0);// ganti dari statusTextField
    platTextField.setEnabled(true);
    searchTextField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hargaTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tampilSemuaButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cariButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMobil = new javax.swing.JTable();
        platTextField = new javax.swing.JTextField();
        tipeTextField = new javax.swing.JTextField();
        merkTextField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        simpanButton.setText("Simpan");
        simpanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanButtonMouseClicked(evt);
            }
        });
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tampilSemuaButton.setText("Tampilkan Semua");
        tampilSemuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilSemuaButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Cari");

        jLabel1.setText("Dasboard Admin");

        jLabel3.setText("Plat Nomor");

        jLabel4.setText("Tipe");

        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Merk");

        jLabel6.setText("Harga Sewa(Per hari)");

        jLabel7.setText("Status");

        tblMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblMobil);

        platTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platTextFieldActionPerformed(evt);
            }
        });

        merkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkTextFieldActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaTextField)
                            .addComponent(tipeTextField)
                            .addComponent(merkTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(platTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tampilSemuaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cariButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cariButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(simpanButton)
                                .addGap(18, 18, 18)
                                .addComponent(updateButton)
                                .addGap(18, 18, 18)
                                .addComponent(hapusButton)
                                .addGap(18, 18, 18)
                                .addComponent(tampilSemuaButton)
                                .addGap(38, 38, 38)
                                .addComponent(clearButton)
                                .addGap(38, 38, 38)
                                .addComponent(BackButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(platTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tipeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(merkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanButtonMouseClicked
        String plat = platTextField.getText();
        String tipe = tipeTextField.getText();
        String merk = merkTextField.getText();
        String harga = hargaTextField.getText();
        String status = cmbStatus.getSelectedItem().toString();

        int statusInt = convertStatusToInt(status);

        controller.tambahMobil(plat, tipe, merk, harga, statusInt);
        
        loadData();
        clearForm();
        JOptionPane.showMessageDialog(this, "Data mobil berhasil disimpan");


    }//GEN-LAST:event_simpanButtonMouseClicked

    private void platTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platTextFieldActionPerformed

    private void merkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merkTextFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose(); // Tutup form
        new AdminDashboard().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearForm();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void tampilSemuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilSemuaButtonActionPerformed
        loadData();
    }//GEN-LAST:event_tampilSemuaButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        String plat = platTextField.getText();
        
        if (plat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih mobil yang akan dihapus terlebih dahulu");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus mobil dengan plat " + plat + "?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            controller.HapusMobil(plat);
            loadData();
            clearForm();
            JOptionPane.showMessageDialog(this, "Data mobil berhasil dihapus");
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String plat = platTextField.getText();
        String tipe = tipeTextField.getText();
        String merk = merkTextField.getText();
        String harga = hargaTextField.getText();
        String status = cmbStatus.getSelectedItem().toString();

        int statusInt = convertStatusToInt(status);

        controller.updateMobil(plat, tipe, merk, harga, String.valueOf(statusInt));
        
        loadData();
        clearForm();
        JOptionPane.showMessageDialog(this, "Data mobil berhasil diupdate");

    }//GEN-LAST:event_updateButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        String keyword = searchTextField.getText().trim();
    
    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan kata kunci pencarian");
        return;
    }
    
    // Panggil method search dari controller
    List<Mobil> hasilPencarian = controller.cariMobil(keyword);
    
    // Tampilkan hasil pencarian di tabel
    tampilkanHasilPencarian(hasilPencarian);
    clearForm();
    }//GEN-LAST:event_cariButtonActionPerformed
    
    private void tampilkanHasilPencarian(List<Mobil> hasilPencarian) {
    DefaultTableModel model = (DefaultTableModel) tblMobil.getModel();
    model.setRowCount(0); // Bersihkan tabel
    
    if (hasilPencarian.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tidak ditemukan data mobil yang sesuai");
        return;
    }
    
    for (Mobil m : hasilPencarian) {
        String statusStr = convertIntToStatus(m.getStatus());
        model.addRow(new Object[] {
            m.getPlat(), 
            m.getTipe(), 
            m.getMerk(), 
            m.getHargaSewa(), 
            statusStr
        });
    }
    }
    
    private void tblMobilMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tblMobil.getSelectedRow();
        if (selectedRow >= 0) {
            platTextField.setText(tblMobil.getValueAt(selectedRow, 0).toString());
            tipeTextField.setText(tblMobil.getValueAt(selectedRow, 1).toString());
            merkTextField.setText(tblMobil.getValueAt(selectedRow, 2).toString());
            hargaTextField.setText(tblMobil.getValueAt(selectedRow, 3).toString());
            
            String status = tblMobil.getValueAt(selectedRow, 4).toString();
            cmbStatus.setSelectedItem(status);
            
            platTextField.setEnabled(false);
        }
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton cariButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField hargaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField merkTextField;
    private javax.swing.JTextField platTextField;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JButton tampilSemuaButton;
    private javax.swing.JTable tblMobil;
    private javax.swing.JTextField tipeTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    private void tampilkanSemuaMobil() {
        List<Mobil> daftarMobil = controller.getAllMobil();

        DefaultTableModel model = (DefaultTableModel) tblMobil.getModel();
        model.setRowCount(0); // clear data lama

        for (Mobil m : daftarMobil) {
            model.addRow(new Object[]{
                m.getPlat(), m.getTipe(), m.getMerk(), m.getHargaSewa(), m.getStatus()
            });
        }
    }


}
